pantheon-systems/pantheon-wordpress-edge-integrations

plugin.php

A couple things I noticed in the main plugin file:
* We should declare the Pantheon\EI namespace. We might actually want to make a Pantheon\EI\WP namespace so we don't clash with the Pantheon\EI namespace in the Edge Integrations library, but maybe we burn that bridge when we get to it.
* We shouldn't need to manually require `inc/namespace.php` -- that should be loaded by the Composer autoloader (it just wasn't working with the way I set up the PSR-4 autoloading).
I went back and forth trying to decide if it was worth it to require `vendor/autoload.php` manually if the autoloader wasn't working for some reason. I ultimately decided that as long as this plugin is installed via Composer, that would never be an issue, as the autoloader would trickle down to the root Composer autoloader, and …

Update the plugin loader

---

composer.json
tests/Test.php

* Switches the initial unit test from just an example to something that actually does something.
* Updates the composer autoloading to use file autoloading instead of PSR-4. This is somewhat more intuitive and gives us more control and options if multiple namespaces exist in the same directory (which might be the case in /inc
* Removes the `autoload-dev` param in composer at all. This was only being used to PSR-4 autoload `\\Tests` which isn't how they're called at all and isn't used or necessary.

Update unit tests

---

composer.json
plugin.php

Check if `\Pantheon\EI\WP\bootstrap()` exists. If it doesn't exist, we didn't autoload `inc/namespace.php` which means the Composer autoloader isn't being used. In that case, load `vendor/autoload.php`. 
We want to use the Composer autoloader because we _also_ need it for the `pantheon-edge-integrations` global library.
Also, this PR adds a syntax checking script and includes that in `composer lint`

[EI-27] Maybe manually load the Composer autoload file 

---

inc/geo.php
tests/geoTest.php

This PR mostly handles adding filters and a hook inside `get_geo`. Geo allowed values are broken out into a separate, smaller function and the filter is moved into that function. Filters are all validated with discrete unit tests.

[EI-18] geo hooks

---

composer.json
composer.lock

We should be requiring `dev-main`. We weren't, so it was causing an issue when updating lower packages because the branch no longer exists.
Ideally, we should be requiring a specific version, but until we have a first release, we should assume `dev-main`.

change the pantheon-edge-integrations dependency

---

composer.json
composer.lock

In order to allow different versions of the edge integrations library (esp during development) we should allow any version of edge integrations to be required without locking to a specific version in our plugin

Downgrade edge-integration-version requirement

---

composer.json
composer.lock
inc/geo.php
inc/namespace.php
tests/Test.php
tests/geoTest.php
tests/interestTest.php

Updates the plugin to accomodate for recent VCL changes:
* adds/updates support for a different set of geo data
* actually sends the vary headers for `Interest` and `Audience-Set`
* cleans up the code
* adds additional filters
* updates unit tests
This PR is dependent upon https://github.com/pantheon-systems/pantheon-edge-integrations/pull/13 and adds that branch as a dependency for the tests and functions to work

[EI-66,EI-65] Vary headers

---

.github/workflows/build.yml
.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/test.yml
README.md
pantheon-wordpress-edge-integrations.php

With these updates, `main` essentially becomes a stable development branch. Once a PR is made against `build` the new action, `build.yml`, will compile assets and make a commit to the PR.
The release workflow would be similar to the following:
1. Create a pull request with production-ready code from `main` against `build`.
2. After automation makes the commit containing the build files, merge the PR into `build`.
3. Locally checkout the `build` branch and pull the latest.
4. Create a new tag: `git tag major.minor.patch`
5. Push the tag to the repo: `git push origin tag major.minor.patch`. This step triggers `release.yml` which will create a new release containing the compiled source.
6. Update `main` version to `major.minor.patch-dev`.
Future development work should always be done off the …

[EI-60] Alter actions for new release process

---

inc/namespace.php

This will fix the warning on the [PR 23](https://pr-23-wp13n.pantheonsite.io/) site.
This hook is run in `Interest\bootstrap` [here](https://github.com/pantheon-systems/pantheon-wordpress-edge-integrations/blob/fix-set-interest-header/inc/interest.php#L21).

Fixes call_user_func_array warning

---

inc/geo.php
tests/geoTest.php

When calling `get_geo` and passing a value that does not exist, we get an "undefined array key" PHP fatal error.
This PR adds graceful handling in the eventuality that we're requesting data that is _allowed_ but was not returned from the CDN.

Fix "undefined array key" error

---

.github/workflows/changelog.js
.github/workflows/release.yml
CONTRIBUTING.md
README.md
composer.json
package-lock.json
package.json

Reformats the readme to work as a wp.org readme.txt file.
Moves all the workflow/developer docs to `contributing.md`
Also adds some workflow stuff to automatically generate the Changelog (see https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/#comment-44096) 
We will probably want to break these out into a separate Deploy script when we're ready to publish on wp.org, so I'm commenting the workflows out for now.

[EI-67] Make README wp.org compatible

---

.github/workflows/build.yml

Builds are failing because `config/webpack.config.js` doesn't exist after it's been `rm -rf`'d. 
This PR moves the ~`rm -rf config/` to after the build is complete~ `npm run dev` up to avoid the error.

Don't remove the config before build

---

inc/namespace.php
tests/Test.php

In the WordPress plugin, we aren't actually setting the vary headers. 
The `set_vary_headers` function here: 
https://github.com/pantheon-systems/pantheon-wordpress-edge-integrations/blob/29f686ae6828eac1166a40af75f31987bf6d4276/inc/namespace.php#L55-L62
...is supposed to set the headers, but that function is never actually called.
This PR
* simplifies the `header` function call by sending it a concatenated list of headers rather than looping through the available options
* unsets the unsupported vary header keys
* fires set_vary_headers on init

[EI-85] Set Vary headers

---

.github/workflows/build.yml
assets/js/interest-count.js

This PR attempts to fix the failing release builds:
* fixes the `no-unused-vars` webpack build error coming from `cookieExpiration` being defined but unused
* adds the minified javascript file to the committed build file and removes the unminified file
* removes the `npm run dev` which removes the minified file if it's run after `npm run build`
Build test: https://github.com/pantheon-systems/pantheon-wordpress-edge-integrations/pull/70/commits/c9888e6f0319fcf0ebfae55663ed563f5c03f2fd

[EI-84] fix failing builds

---

assets/js/assets.js
assets/js/gtm-headers.js
assets/js/interest-count.js
composer.json
composer.lock
inc/analytics.php
inc/interest.php
inc/namespace.php

There's a lot here, y'all. This is a biggie.
The key concept of this PR is to natively integrate with Google Analytics and Google Tag Manager. To support this, a new `analytics.php` namespace is created as well as a `gtm-headers.js` file similar to the [`gtm_headers.js`](https://github.com/pantheon-systems/smart_content_cdn/blob/main/js/gtm_headers.js) file in [Smart Content CDN](https://github.com/pantheon-systems/smart_content_cdn). The analytics code:
* adds the code block that should appear in the HTML `<head>`
* adds the code block that should appear in the HTML `<body>`
* passes variables in PHP to the javascript object
* adds a function -- `Analytics\get_gtm_code` which returns the GTM code, if one is set
* adds a filter that allows the GTM code to be set programmatically. If set …

[EI-101] integrate GA & GTM

---

README.md
package.json
pantheon-wordpress-edge-integrations.php

This bumps the plugin version to 0.2.12-dev and 0.2.12 in `package.json`. Bumps stable tag in readme to 0.2.11.

bump versions

---

inc/analytics.php

Wrap the geo data in a json decode function; we don't want an encoded string passed to the javascript

[EI-93] json_decode the geo data

---

CONTRIBUTING.md

I don't think there's any reason why version bumps need to be in a PR, it just slows down the process. This updates the last step to advise to just push version bumps to `main`.
Also, I think it's easier to create the tag at the same time as the release is drafted and it should still trigger the same release workflow. If this is not the case, I'm happy to adjust. In that case, I think it would make sense to write a script that automates the process.

update release process

---

inc/interest.php
inc/namespace.php

There are a couple hook points where things were not being set or filtered correctly. This PR should take care of them. This is a continuation of https://github.com/pantheon-systems/pantheon-edge-integrations-consent-management/pull/17
* Sets the vary headers very late, allowing other plugins to hook in and filter the supported headers earlier.
* fixes the array of supported vary headers
* does not set any post terms if the post type is not supported

[EI-52] fix hook points

---

inc/namespace.php
tests/Test.php

This PR adds a new `edge_integrations_enabled` function that checks that we have header data for any of the enabled vary headers.

[EI-111] Edge Integrations enabled function
